baseURL                       = "https://wisnuwiry.space/"
languageCode                  = "id"
title                         = "Wisnuwiry"
theme                         = "personal-site"
summaryLength                 = 10

[Author] # Used in authorbox
  name                        = "Wisnu G. Saputra"
  bio                         = "Flutter | Mobile Tech Enthusiast | Software Engineer at KodingWorks. Saya juga suka blogging dan mempelajari hal teknologi baru."
  avatar                      = "img/avatar.png"
  job                         = "Software Engineer"
  gender                      = "male"
  email                       = "wisnuwiry@gmail.com"
  donate                      = true
  
[Params]
  description                 = "Sebuah catatan dan blog pribadi saya. Saya juga akan membagi tentang pengalaman saya dan teknologi-teknolgi yang saya gunakan/pelajari atau yang sedang populer." # Site Description. Used in meta description
  images                      = ["img/avatar.png"]
  copyright                   = "Wisnuwiry" # Copyright holder, otherwise will use .Site.Title
  opengraph                   = true # Enable OpenGraph if true
  twitter_cards               = true # Enable Twitter Cards if true
  mainSections                = ["post"] # Set main page sections
  projectSections             = ["project"] # Set main page sections
  dateFormat                  = "January 02, 2006" # Change the format of dates
  # customCSS                 = ["css/custom.css"] # Include custom CSS files
  customJS                    = []
  mainMenuAlignment           = "right" # Align main menu (desktop version) to the right side
  authorbox                   = true # Show authorbox at bottom of single pages if true
  comments                    = true # Enable comments for all site pages
  related                     = true # Enable Related content for single pages
  relatedMax                  = 5
  mathjax                     = false # Enable MathJax for all site pages
  hideNoPostsWarning          = false # Don't show no posts empty state warning in main page, if true
  fontUnit                    = "em"
  largestFontSize             = 2.5
  smallestFontSize            = 1
  googleSearchConsole         = "HD_A_of8GbY1AMjHR-nwxsFAZUf7xbfUIuWDUlLEvMg"
  GoogleAnalytics             = "UA-147337173-1"
  fb_admins                   = 100023577212451
  fb_app_id                   = 192065405413624
  paginateLength              = 5
  #adsenseId                   = "ca-pub-6496667754181154"
  customSearchId              = "004021659876411083349:a2ysxpichpc"
  endMessagePost              = "Terdapat kesalahan penulisan, typo, ataupun juga kurang sesuai dalam penulisan, bantu Saya"
  editContentPageLink         = "https://github.com/wisnuwiry/blog-v2/edit/master/content/"
  formspreeId                 = "xjvperzz"
  subTitle                      = "Personal site, Blog, and Portfolio"

[Params.Hero]
  title                       = "A Personal Site By WisnuWiry"
  desc                        = "Welcome to my Blog :)"

[Params.Entry]
  meta                        = ["date", "categories"] # Enable meta fields in given order
  toc                         = true # Enable Table of Contents
  tocOpen                     = false # Open Table of Contents block. Optional

[Params.Featured]
  previewOnly                 = false # Show only preview featured image

[Params.Comments]
  repository                  = "wisnuwiry/blog-v2"

# Navigation bar
[menu]

[[menu.main]]
identifier = "Post"
pre = "üìù"
url = "/post" 
weight = 1 

[[menu.main]]
identifier = "Snippet"
pre = "‚öíÔ∏è"
url = "/snippet" 
weight = 2 

[[menu.main]]
identifier = "Project"
pre = "üöß"
url = "/project" 
weight = 3 

[[menu.main]]
identifier = "About"
pre = "üòÉ"
url = "/about" 
weight = 4

[[menu.main]]
identifier = "Contact"
pre = "ü§ô"
url = "/contact" 
weight = 5

[Params.Breadcrumb]
  enable                      = true # Enable breadcrumb block globally
  homeText                    = "Home" # Home node text

[Params.Social]
  twitter                     = "wisnuwiry"
  telegram                    = "wisnuwiry"
# instagram                   = "wisnuwiry"
  linkedin                    = "wisnu-saputra"
  github                      = "wisnuwiry"
  gitlab                      = "wisnuwiry"
  medium                      = "wisnuwiry"

[Params.Share] # Entry Share block
  facebook                    = true
  twitter                     = true
  reddit                      = true
  telegram                    = true
  linkedin                    = true
  pinterest                   = true

# Web App Manifest settings
# https://www.w3.org/TR/appmanifest/
# https://developers.google.com/web/fundamentals/web-app-manifest/
[Params.Manifest]
  name                        = "Wisnuwiry"
  shortName                   = "Wisnuwiry"
  display                     = "standalone"
  startUrl                    = "/?utm_source=homescreen"
  backgroundColor             = "#8dc153"
  themeColor                  = "#1da1f2"
  description                 = "Personal Site By Wisnuwiry"
  orientation                 = "portrait"
  scope                       = "/"

[outputFormats]
  [outputFormats.MANIFEST]
    mediaType                 = "application/json"
    baseName                  = "manifest"
    isPlainText               = true
    notAlternative            = true

[taxonomies]
    category = "categories"
    series = "series"
    tags = "tags"
    
[outputs]
  home                        = ["HTML", "RSS", "MANIFEST"]

enableRobotsTXT               = true

# Pagination
Paginate                      = 5
 
[sitemap]
  changefreq = "daily"
  changeFreqPage = "monthly"
  filename = "sitemap.xml"
  priority = 1
  priorityPage = 0.5

# Code
[markup]
  # defaultMarkdownHandler    = "blackfriday"
  # [markup.goldmark]
  [markup.highlight]
    codeFences                = true
    guessSyntax               = false
    hl_Lines                  = ""
    lineNoStart               = 1
    lineNos                   = true
    lineNumbersInTable        = true
    noClasses                 = false
    style                     = "dracula"
    tabWidth                  = 4
  [markup.tableOfContents]
    endLevel                  = 3
    ordered                   = false
    startLevel                = 2
